//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LazyProger.ScenesConstantNames
{
    
    
    public class Scenes
    {
        
        public static string Gameplay = "Gameplay";
        
        public static string Level1 = "Level1";
        
        public static string Level2 = "Level2";
        
        public static string MainMenu = "MainMenu";
        
        public static string Startup = "Startup";
    }
}
